spring.application.name=measurement-service
server.port=8081
server.servlet.context-path=/measurement
# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Optional but recommended
eureka.instance.prefer-ip-address=true